### ISSUE TITLE
Add component section option

### ISSUE THREAD

**Issue by miniscruff** [miniscruff/changie#116]
Add option for component headers.

So instead of:
header > kind > fragment

It can be:
header > component* > kind* > fragment
where both component and kinds are optional

**Comment by EmilyRosina** [comment]
I have been searching for hours but maybe it's just easier asking here..

I use kind and component, but I want the hierarchy to be:
`header` > `kind` > `component` > `fragment`

e.g.
```md
Version x.x.x _03/03/2023_

### ADDED
- **Component A**
  - Some change
  - Another change
- **Component B**
  - Some other change

### FIXED
- **Component B**
  - Some fix  
```

Is that even possible?

**Comment by miniscruff** [comment]
@EmilyRosina Hello Emily, there is no current way of reordering kinds and components. The only real option would be to use kinds as components and vice versa if you want.

**Comment by EmilyRosina** [comment]
> there is no current way of reordering kinds and components.

Ah ok, thank you for confirming my suspicion. It's a shame but glad to have an answer so quickly.

> The only real option would be to use kinds as components and vice versa if you want.

At first I thought that may work 🤔 but I need the weighting applied to ADDED/FIXED etc to still be associated with bump of patch/minor/major versions.. which I don't think is possible if I switch them?

**Comment by miniscruff** [comment]
> At first I thought that may work 🤔 but I need the weighting applied to ADDED/FIXED etc to still be associated with bump of patch/minor/major versions.. which I don't think is possible if I switch `kind` and `component`?

Correct, you would need to use manual bump values since your auto mode configs would be on the components at that point. Not ideal for sure.

Not a trivial request to support via a config option either since it wouldn't be a simple toggle it would have to alter the sort algorithm and rendering order which are fixed together and one of the base assumptions we have. 

Well it would be easy if it was just a bool, but I think we would want to allow any sort order and that would allow you to have the headers in the order you want. But it would be complex for sure.

**Comment by EmilyRosina** [comment]
> > At first I thought that may work thinking but I need the weighting applied to ADDED/FIXED etc to still be associated with bump of patch/minor/major versions.. which I don't think is possible if I switch `kind` and `component`?
> 
> Correct, you would need to use manual bump values since your auto mode configs would be on the components at that point. Not ideal for sure.
> 
> Not a trivial request to support via a config option either since it wouldn't be a simple toggle it would have to alter the sort algorithm and rendering order which are fixed together and one of the base assumptions we have.
> 
> Well it would be easy if it was just a bool, but I think we would want to allow any sort order and that would allow you to have the headers in the order you want. But it would be complex for sure.

Sounds great if you had the time to support it :heart: :rocket: 
I would definitely make use of it for sure! But yeah, doesn't really sound like a quick nor simple fix :bouquet: 

---

For the time being, I've opted for removing `Component` and using a custom `enum` called `Category` instead.
I needed to admit defeat for nesting list items, but am ok to settle on bolding the `Custom.Category` before the `Change` for each list item. I also overrode the `fragmentFileFormat` to keep the same file naming as I had when using `Component`.

```yaml
fragmentFileFormat: '{{.Custom.Category}}-{{.Kind}}-{{.Time.Format "20060102-150405"}}'
```

```md
Version x.x.x _03/03/2023_

### ADDED
- **Component A** Some change
- **Component A** Another change
- **Component B** Some other change

### FIXED
- **Component B** Some fix  
```

---

Thank you, for both the quick replies and `changie` as a whole.
It really is a great tool, that I use at work and for my side projects. It's invaluable :gem:
