### ISSUE TITLE
Switch prompt tool to survey

### ISSUE THREAD

**Issue by miniscruff** [miniscruff/changie#119]
promptui has a select and prompt feature but that is all.

https://github.com/AlecAivazis/survey has many more prompt options such as mutliline, confirm and multiselect.
I think moving to survey is going to be better regardless as it is in more active development.

The selection of prompt tool should not dictate much in changie, a small abstraction should work and can reduce the testing overhead of using stdin strings for stuff.
(TODO design the above)

**Comment by miniscruff** [comment]
Could be a change for 2.0 but might be completely backwards compatible and be release in 1.x if we choose to do it then.

**Comment by jonatan5524** [comment]
I am new to this repo, I would like to work on this issue.

**Comment by miniscruff** [comment]
> I am new to this repo, I would like to work on this issue.

If you want to get started a little easier I think #238 is simpler btw, just a thought.

**Comment by jonatan5524** [comment]
> > I am new to this repo, I would like to work on this issue.
> 
> If you want to get started a little easier I think #238 is simpler btw, just a thought.

I will go through the codebase to see if I am getting what I will need to do for this issue. About the issue itself, I have some questions I will mention in the relevant issue.

**Comment by miniscruff** [comment]
Created a PR in survey to fix a windows bug https://github.com/AlecAivazis/survey/pull/458, then I will get this merged

**Comment by miniscruff** [comment]
Going to use https://github.com/cqroot/prompt instead
