### ISSUE TITLE
Allow for accessing "Previous Version" in versionFormat

### ISSUE THREAD

**Issue by rocktavious** [miniscruff/changie#225]
**Is your feature request related to a problem? Please describe.**
I would like to use a custom version format that allows the version header be a link to the changes

```yaml
versionFormat: '## [{{.Version}}](https://github.com/miniscruff/changie/compare/{{.PreviousVersion}}...{{.Version}})'
```

So it would emit the markdown

```
## [v0.2.0](https://github.com/miniscruff/changie/compare/v0.1.0...v0.2.0) 
```

**Describe the solution you'd like**
It should be as simple as pipeing the "current version" of the batch command before increment as one of the valid batchData things.

**Describe alternatives you've considered**
It seems pretty straightforward ask so I had not considered anything things since the syntax for the formatting requires the previous version

**Comment by miniscruff** [comment]
I commented this on the pull request, but will add it here as well. Because I am rewriting the batch and batch test files I will not be accepting your PR directly but I will add this value during or directly after the rewrite.
