### ISSUE TITLE
New Header/Footer format options don't match between code and docs

### ISSUE THREAD

**Issue by emmyoop** [miniscruff/changie#253]
**Description**
In the docs this new field is called [`versionHeaderFormat`](https://changie.dev/config/header-footer/#versionheaderformat) and [`versionFooterFormat`](https://changie.dev/config/header-footer/#versionfooterformat) but in the code it's 

https://github.com/miniscruff/changie/blob/4c3360d866a95506f18d959ff1fc863936cd6003/core/config.go#L68-L69

So far everything else seems to work.  I'm happy to make this simple change (either in the docs or rename in the code) but was wondering which name you would prefer?

My two cents are that `footerFormat` seems more consistent with the other keys (`kindFormat`, `changeFormat`, etc)

**What happened**
Using the field as stated in the docs just swallows it.

**Expected behavior**
Docs match code.

**Comment by miniscruff** [comment]
Oh oops, looks like between the two PRs I accidentally created two variables instead of one. Let me fix that.

**Comment by miniscruff** [comment]
Ok the docs are updated now, sorry about that.
