### ISSUE TITLE
More control over changie next --prerelease

### ISSUE THREAD

**Issue by fredbi** [miniscruff/changie#282]
**Is your feature request related to a problem? Please describe.**
I am using prereleases (aka release candidates) and release with a suffix.
Ex: v1.5.0, v1.5.1-staging, v1.5.2-staging, v1.5.2

Bumping a prerelease with `changie next` currently doesn't work when both kinds are present.
Ex:
In `.changes`, I have a `v1.5.0.md` and a `v1.5.1-staging.md` created.
Without the `--prerelease` flag, `changie next ...` works fine:
```
changie next patch
v1.5.1
changie next minor
v1.6.0
```

But with the `--prerelease flag`, I have the same result, with the prerelease suffix.
I would expect that `changie next --prerelease` checks the latest version _with a suffix_ rather than the latest release.
Ex: 
how it behaves now:
```
changie next patch --prerelease staging 
v1.5.1-staging
```
how I would expect it to behave:
```
changie next patch --prerelease staging 
v1.5.2-staging
```

I understand that the existing feature is not wrong. Actually, it behaves as expected when there is NO pre-release following the
latest release yet. For example:
```
v1.5.0
v1.5.1-staging
v1.5.1
```
And this is ok:
```
changie next patch --prerelease staging
v1.5.2-staging
```

**Describe the solution you'd like**
I'd like to implement a new flag to `changie next` to more accurately define the result, according to expectations.
* by default: current behavior
* `--from-latest=prerelease` (with `--prerelease` flag set): evaluates the latest version, including the ones suffixed as prereleases and bumping from there if any is found

**Describe alternatives you've considered**
I've been tinkering with resolving the expected next release, either manually, or inferring it from git tags, but in the end, this
is always more complex and fuzzing the clear and logical path set when I've introduced changie to my repos.

**Additional context**

**Comment by miniscruff** [comment]
I am not quite sure I follow here, is your current workflow meant to handle multiple staging releases before a final?
Going from 1.5.1-staging to 1.5.2-staging would be wrong for semver, the prerelease version denotes it is not yet stable and released. If we instead bump the patch version we would of skipped a patch release.

If you want to release more than one staging build before the final you can add a number or something to your prereleases.
Something like:
```
v1.5.0
v1.5.1-staging.1 # changie next patch --pre staging --pre 1
v1.5.1-staging.2 # changie next patch --pre staging --pre 2
v1.5.1-staging.N # # changie next patch --pre staging --pre N
v1.5.1 # no more staging, it is now stable, so remove the prerelease tags
```
You could also use the `--meta` option but its more or less the same as above.

**Comment by fredbi** [comment]
Yes, my workflow handles multiple staging releases (aka release candidates) before a final release.

I realize that this specific behavior is specific to patch, and is implied by the semver package, specifically for IncPath: here https://github.com/Masterminds/semver/blob/7bb0c843b53d6ad21a3f619cb22c4b442bb3ef3e/version.go#L283

So this confirms your explanation.

I understand that our workflow is not 100% semver compliant: this is due to the very long period spent as "release candidate" and we get patches, features etc, while still not in full release. Hence the continuous incrementing patches, features etc.

What I am proposing here is not to depart from the the semver compliance as the default behavior, just to add some leeway to get more control when we have to (as is the case for me now).

I've to find a more explicit flag name, though.

I've just tested the extended behavior, now trying to add this new feature with minimal change in your code.

**Comment by miniscruff** [comment]
Hmm, ok. I am open to improvements but if it goes against semver it might be a hard sell. 
Follow up question, what happens to v1.5.1 in your example?
If you go from v1.5.1-staging to v1.5.2-staging where does v1.5.1 go? Was it released or just skipped?

**Comment by fredbi** [comment]
@miniscruff I've pushed a PR that proposes a new "--force-patch" flag. It is explicit about possibly breaking strict semver.
My point is just to provide the user with more control, not to break semver.

To answer your question, yes v1.5.1 would be normally just be skipped.

**Comment by fredbi** [comment]
I am not arguing about whether it is better or not.
I have existing repos, this is how they work and I am not going to change that any time soon. I need this leeway, so here it is.
This is it. This is a pragmatic change about a pragmatic issue.

I am not imposing anything: feel free to accept my proposal or not.

**Comment by fredbi** [comment]
ok. Closed. I am moving on with my fork.
