### ISSUE TITLE
changie latest support for pre-releases

### ISSUE THREAD

**Issue by fredbi** [miniscruff/changie#283]
**Is your feature request related to a problem? Please describe.**
I could use a `--prerelease` flag for the `changie latest` CLI command.

At the moment, my use-case mixes releases and pre-releases, so `changie latest` is of virtually no use.

```
v1.5.0
v1.5.1-staging
```

```
changie latest
v1.5.1-staging
```
Ex 2:

```
v1.5.0
v1.5.1-staging
v1.5.2-xyz
```

```
changie latest
v1.5.2-xyz
```

**Describe the solution you'd like**
* add a `--prerelease=suffix`, `--no-prerelease` flagd to the `changie latest` command
* default behavior: current behavior
* expected behavior with flags (from above situation)
```
changie latest --no-prerelease
# instead of v1.5.1-staging
v1.5.0
```
```
changie latest --prerelease staging`
# instead of v1.5.2-xyz
v1.5.1-staging
```

**Describe alternatives you've considered**
Considered at some point to change tack completely and handle my releases from git tags entirely, using change only to generate release notes and not to drive release bumps.

**Additional context**

**Comment by miniscruff** [comment]
I am not sure about the suffix part of the parameter, semver org has a sorting method defined here https://semver.org/#spec-item-11 that can be used. Would just `changie latest --prereleases` work where it finds the latest prerelease? This would make v-alpha < v-beta < v-rc1 < v-rc2.

**Comment by fredbi** [comment]
yes `--prereleases` works better. I can do that.

**Comment by miniscruff** [comment]
Added directly to main
