### ISSUE TITLE
changie next v1.2.3

### ISSUE THREAD

**Issue by fredbi** [miniscruff/changie#284]
**Description**
Maybe I am missing something, but the behavior of the following command is
a bit counter-intuitive (accepted, but not really documented):

1. Form 1:
```
changie next v.1.2.3
v1.2.3
```
2. I would understand the meaning of `changie next patch v1.2.3` (unsupported) or similar command.
3. I would understand the meaning of `changie next v1.2.3` to some automatically determined minor/patch/major based on the content of some unreleased changie tickets (none of this happens).

But the current behavior is a puzzle to me. 

Unless there is a specific rationale for it, I would prefer either of the following fixes:
1. Form (1) returns an error (expect patch|minor|major)
2. Support form (2) (extra arg)
3. Support form (3) (extra complexity, some automagical/under-the-hood stuff is happening, maybe not a good idea).

**Reproduction Steps**
1. Run '...'
1. Edit config '...'
1. Then run '...'
1. See error

**What happened**
What did you see happen?

**Expected behavior**
What did you expect to happen?

**Additional context**

**Comment by miniscruff** [comment]
Ah yea, that is currently an undocumented "feature" in that `next` accepts a version string and will just return it as is. This is mostly cause next and batch share a common util function.
https://github.com/miniscruff/changie/blob/a32e4a511e590d537b9508d37c780d1d1c7436c4/core/utils.go#L73

In batch a version is acceptable and useful, for next it is not but it does not do any sort of checks to allow or not allow it. I simply did not mention in the docs that you can pass in a version string as, well it is quite pointless as it would just return that version. 

Not allowing any string other then major, minor or patch for next would work.

**Comment by fredbi** [comment]
> Not allowing any string other then major, minor or patch for next would work.

Yes agree. Just a nitpick anyway, but was curious about the intent. I can fix that too shortly.
