### ISSUE TITLE
Keep old changelong safe when batching

### ISSUE THREAD

**Issue by smsimone** [miniscruff/changie#308]
**Is your feature request related to a problem? Please describe.**
In my workflow, when I have something that's ready to be tested, I launch my pipeline which will read the changelog merged by changie.
It happens that for a single version I have to make 3-4 builds because of fixes, but there's no way to keep the old changelog and merge it with the new one.

**Describe the solution you'd like**
Instead of overwriting the old changelog, it would be nice to keep the old changelog safe and adding the new lines on the top of it.
Ex.
> Old changelog:
> ```plain
> Fixes:
>- foo
>- bar
>```

> New changelog
> ```plain
> Fixes:
> - new fix
> - foo
> - bar
>```

**Comment by miniscruff** [comment]
Closing as this does not work in the Changie flow, I think you can use `--keep` or maybe `--dry-run` for prereleases. Feel free to bring up the issue again if you are not sure.
