### ISSUE TITLE
Documentation issue in _index.md

### ISSUE THREAD

**Issue by debugwand** [miniscruff/changie#309]
Video doesn't play properly, gets as far as halfway through filling out the custom settings for github author then freezes. Controls don't work to continue play or go to another point in the stream.

Thanks.

**Comment by miniscruff** [comment]
hmm ok, not sure what I can do since I am just using the asciinema project, I might transition the website videos to mp4s to resolve this sort of thing.

**Comment by miniscruff** [comment]
Can you share what browser and version you are using, it may be related to that.
