### ISSUE TITLE
Make change fragment name configurable

### ISSUE THREAD

**Issue by hemeroc** [miniscruff/changie#311]
**Is your feature request related to a problem? Please describe.**
We use a ticket system and each of our changes is related to exactly one ticket.
This should be reflected by having the ticket name in the changie file. (possible via custom choice)
Changie files must be archived and kept in the repository when doing a release. (possible via `keep` flag)

**Describe the solution you'd like**
Have a changie config value that allows to define the name pattern for the change fragments e.g. use the custom issue value.

**Comment by miniscruff** [comment]
This sounds fine, it does make sense that you should be able to customize this filename considering all the other options changie has. I have been meaning to refactor the new pipeline a bit so I can handle that as well.

If possible can you give me an example of what your template might look like?

**Comment by Seraf** [comment]
Hello, we also have this use-case, we would like to use the component as part of the naming.
The goal is to ensure we won't have a collision when combining the fragments of multiple repositories

**Comment by miniscruff** [comment]
> Hello, we also have this use-case too, we would like to use the component as part of the naming. The goal is to ensure we won't have a collision when combining the fragments of multiple repositories

The current format includes component and kind if they are configured so this should be fine. I will allow you to use a configurable template though so you can add custom options or just static values if you want.

**Comment by miniscruff** [comment]
Will be part of v1.7.0 soon
