### ISSUE TITLE
Support alphanumerical releases

### ISSUE THREAD

**Issue by tq-steina** [miniscruff/changie#344]
**Is your feature request related to a problem? Please describe.**
Currently `changie` only support semver based releases, e.g. v1.3.5, v2.0 and so on. Several of our projects have a different naming schema, for example `hardknott.TQMa335x.BSP.SW.0122` (see https://github.com/tq-systems/meta-tq/tags for more).

All parts parts separated by `.` are orthogonal and are changed within their own meaning.

**Describe the solution you'd like**
I would like to support arbitrary release names, including this naming schema. Of course in that case there is no `major`, `minor`, `patch` or `next`. Within this schema the release would have to be specified explicitely every time.

Merging the release notes should be done by timestamps as well.

**Describe alternatives you've considered**
For us semver is not suitable, because the first part already is the [Yocto release name](https://wiki.yoctoproject.org/wiki/Releases). There is almost no relation bewteen for example `hardknott.TQMa335x.BSP.SW.0001` and `zeus.TQMa335x.BSP.SW.0001`.

**Comment by miniscruff** [comment]
So after a little bit of time to think about this I have a few questions as well as maybe a potential solution.
First, Changie versioning support is not coincidentally anything that https://github.com/Masterminds/semver supports. By definition it sounds like semver only but can also support [calver](https://calver.org/) or similar versions where sorting can be done numerically. Therefore, your suggestion of supporting alphanumerical falls into a bit of an issue.

However, that is not the only issue, namely this part here: 

    All parts parts separated by . are orthogonal and are changed within their own meaning.

This is particularly difficult to solve as version sorting used by the merge command is done via filenames. Sorting by timestamps is not possible as the timestamp is not used anywhere in the batch output and therefore can not be used in the merge command. You can sort of get around this if you were to use Calver as the date would be the version and thus would auto sort chronologically.

One additional problem is your versions include more than 3 parts, which will most likely cause issues when parsing.

To me it sounds just a little too far outside the range of what Changie is focused on to support this type of versioning.
You would definitely have to fit your project into what Changie is expecting in terms of versioning or make massive changes to a fork and maintain it.

**Comment by tq-steina** [comment]
Thanks for looking into this. I already suspected our current naming schema is not supported (or not supportable at all).

Requiring numbers in front for sorting is understandable and reasonable. Arbitrary suffixes are also possible apparently. But I noticed only 3 number versions are supported. Is there a hard requirement for that? Even releases like `0.1.1.5.4` are sortable. I admit this is theoretical for now, but to support separate stable branches with disjunct release names in the same repository (e.g. `hardknott` and `kirkstone`), the major number has to be sacrificed. Is it possible to add support for multiple levels of numbers?

**Comment by miniscruff** [comment]
I believe the 3 numbers are simply due to the expected major, minor and patch values. It is not a list of numbers it is those 3 values specifically. You can add a list of arbitrary numbers with metadata or any values using the prerelease but those will also be sorted which may not be what you want. semver.org has all the details and all of the values should be supported in changie. That would give you a version something like `0.1.5+hardknott` as metadata or `0.2.3+hardknott.5` where you can add more dot separated values for additional metadata. The version value would still be the first three numbers.

**Comment by tq-steina** [comment]
Thanks for confirmation. So I take right now just major, minor, patch is supported for versioning management. I am aware, that arbitrary suffixes are possible, as you mentioned. Unfortunately releases like `0.1.5+hardknott` and `0.1.5+kirkstone` would be **completely** different and independent. But this is something on a global project scale and should be manageable using different (stable) branches.
Anyway, thanks for your feedback.
