### ISSUE TITLE
Pressing Suppr causes Changie to quit

### ISSUE THREAD

**Issue by agateau** [miniscruff/changie#373]
**Description**

When editing the body of a new entry, if I go back in the line and press Suppr to delete a character, Changie quits.

**Reproduction Steps**
1. Run 'changie new'
1. Select a kind
1. Start typing
1. Press `←` to go back a few characters
1. Press `Suppr`

**What happened**
Changie quits like this:

```
Error: ^D
Usage:
  changie new [flags]

Flags:
  -b, --body string        Set the change body without a prompt
  -c, --component string   Set the change component without a prompt
  -m, --custom strings     Set custom values without a prompt
  -d, --dry-run            Print new fragment instead of writing to disk
  -h, --help               help for new
  -k, --kind string        Set the change kind without a prompt

```

**Expected behavior**
The character under the cursor is deleted.

**Comment by miniscruff** [comment]
I was able to reproduce this once I figured out what the suppr key was :smirk:. I am not sure how to solve this as the prompts are handled by a separate package. I do have plans to swap to a different prompt package, but I will see if the tool can be worked around or if a patch is necessary.

**Comment by agateau** [comment]
Ah sorry, yes, Suppr is the French version. I guess it's most commonly known as Del or Delete :)

Another (related but less annoying) issue which is probably caused by promptui is when I go back with `←`, the character under the cursor is not visible. Here are some screenshots in case this is not clear.

In my shell, it's OK:
![image](https://user-images.githubusercontent.com/3575/193138730-329fd954-19fa-4fae-81f9-c021807f8591.png)

But in Changie, I can't see the `h` under the cursor:
![image](https://user-images.githubusercontent.com/3575/193138881-b2226c7f-0af2-4607-b5c0-f8a931111876.png)

**Comment by miniscruff** [comment]
Yea promptui has a few issues, I have a PR ( #374 ) to switch over to survey which is a little more supported and has more features. ( Not entirely sure why I chose promptui to begin with ) However there are a few issues related to survey I want to tackle first ( currently an issue when inputting invalid answers and repeated lines being output ). If you want to try the survey version feel free.

**Comment by agateau** [comment]
I just tried the branch from your PR, but it looks worse :disappointed: : the cursor is not visible, and arrow keys do not move the invisible cursor.

**Comment by miniscruff** [comment]
Ok well the cursor not being visible was a config I forgot to set. But it seems like arrow keys are not functional in survey at all so no option to go left or right to delete. Someone made an issue for it a while ago but it does not seem like its been picked up. 

Not sure what is better here, a broken delete or no option to go left at all?

I could try and patch promptui but the last update was a year ago and the whole org seems to have stopped working. It seems like survey is more the go to tool for golang. It does support a few other options like editor and multiline so I think moving to survey would be better.

**Comment by agateau** [comment]
I see :/. Does "editor" means the ability to enter the text with the user preferred text editor? That would be a nice alternative.

**Comment by miniscruff** [comment]
Yea that is what it does, I want to add it as an option for customs along with multiselect, multiline and confirm. Maybe an env var or something for "edit body in editor" for those who want to use an editor for the body.

**Comment by agateau** [comment]
Have you looked at what [GitHub Cli](https://github.com/cli/cli) uses? The behavior looks good, and it's written in Go too.

**Comment by miniscruff** [comment]
It uses survey: https://github.com/cli/cli/blob/8fc120d70021e3aa726f742bc840579cab0c334d/go.mod#L6, they seem to extend it a little bit for more advanced editor stuff but shouldn't be a problem. It does seem like the arrow keys exist when I use the latest version. For some reason they don't have the same bug I have locally even with the same version. Quite interesting...

**Comment by miniscruff** [comment]
Ok after looking into it more it seems like they are handling IO streams a lot more, it is way outside the scope of work I feel is reasonable for changie though. Will update survey and then try and get the repeated output in windows fixed.

**Comment by miniscruff** [comment]
@agateau There is an open PR on survey for a windows fix, once that gets updated I will swap over to survey which should fix this issue.

**Comment by agateau** [comment]
Sounds good 👍

**Comment by miniscruff** [comment]
Work will begin soon using a new tool related to this issue: https://github.com/miniscruff/changie/issues/457

**Comment by agateau** [comment]
Looking forward to it, I've heard good things about Bubbletea!

**Comment by miniscruff** [comment]
https://github.com/miniscruff/changie/pull/464 should resolve this issue with the new tool, if you have a minute to try it out. It worked for me.
