### ISSUE TITLE
`new` command with docker gave unexpected results

### ISSUE THREAD

**Issue by llaville** [miniscruff/changie#398]
**Description**
changie `new` command with docker (container version 1.10.0) does not run as expected

**Reproduction Steps**
1. Run `docker run --rm --user $(id -u):$(id -g) --mount type=bind,source=$PWD,target=/src -w /src  ghcr.io/miniscruff/changie:v1.10.0 init` to initialize changie environment
1. Run `docker run --rm --user $(id -u):$(id -g) --mount type=bind,source=$PWD,target=/src -w /src  ghcr.io/miniscruff/changie:v1.10.0 new`
1. See error

**What happened**
Got unexpected results : 
```
Error: ^D
^D
Usage:
  changie new [flags]

Flags:
  -b, --body string        Set the change body without a prompt
  -c, --component string   Set the change component without a prompt
  -m, --custom strings     Set custom values without a prompt
  -d, --dry-run            Print new fragment instead of writing to disk
  -h, --help               help for new
  -k, --kind string        Set the change kind without a prompt
```
I've also tried with `dry-run` option, without success.

**Expected behavior**
Change File generated as expected by the `new` command.

**Additional context**
Docker version 20.10.21, build baeda1f

On my local repository, `git status` command returns this output 
```
On branch 4.9
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   data/reference/extension/xdebug/3/releases.json

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .changes/
        .changie.yaml
        CHANGELOG.md
```

I got same issue after I've commited changes to my local repository (`git commit -m "update xdebug reference to version 3.1.6"`)

```
[4.9 f9645121] update xdebug reference to version 3.1.6
 1 file changed, 6 insertions(+)
```

**Comment by miniscruff** [comment]
Just throwing this out I have not tried it myself, but either you need to add `-it` to get the shell for the prompts or maybe its related to #373 and an issue with promptui.

**Comment by llaville** [comment]
> you need to add `-it` to get the shell for the prompts

Works for me : thanks for the TIP !

**Comment by llaville** [comment]
@miniscruff I suppose I should add this option `-it` to the Docker Installation guide too : #397

**Comment by miniscruff** [comment]
Yea that would be a good plan, maybe two examples one for new using `-it` and one for say batch without any prompt input.
