### ISSUE TITLE
[batch v1.10.0] overwrite current contents

### ISSUE THREAD

**Issue by llaville** [miniscruff/changie#405]
**Description**
With Changie v1.10.0 `batch` command with "version" and existing `.changes/<version>.md` file, and some change fragments, contents are lost
 
**Reproduction Steps**
1. Add some change fragments with `new` command
1. Generate a version with `batch` command (i.e: `batch 4.10.0`)
1. Commit the `.changes/4.10.0.md` file in git repository
1. Add some other change fragments
1. Re-generate the same version with same command (i.e: `batch 4.10.0`)
1. Contents of `.changes/4.10.0.md` has only last change fragments added

**What happened**
Contents of a version file is not merged with previous contents and new fragments 

**Expected behavior**
Don't lost contents of previous file when exists

**Additional context**

Initial contents of version file (i.e: `.changes/4.10.0.md`)
```text

## 4.10.0 - 2022-11-12

### Changed

- `db:build` and `db:release` commands are only available when development mode is active (env var `APP_ENV` sets to `dev`)

```

Add new fragments into `.changes/unreleased` folder

* `.changes/unreleased/Changed-20221114-073757.yaml`
```
kind: Changed
body: Xdebug reference updated to version 3.2.0RC2
time: 2022-11-14T07:37:57.8894676Z
```

* `.changes/unreleased/Fixed-20221114-073426.yaml`
```
kind: Fixed
body: support to Solr 2.6.0 (see commit https://github.com/php/pecl-search_engine-solr/commit/080b98389a2c05ba68bb613e3a266dbf216340de)
time: 2022-11-14T07:34:26.3090988Z
```

Final contents of `.changes/4.10.0.md` after command `batch 4.10.0`
```
## 4.10.0 - 2022-11-14

### Changed

- Xdebug reference updated to version 3.2.0RC2

### Fixed

- support to Solr 2.6.0 (see commit https://github.com/php/pecl-search_engine-solr/commit/080b98389a2c05ba68bb613e3a266dbf216340de)
```

Work around is to keep all change fragments (`batch version -k`) since we started a new version until it is really merge into CHANGELOG.md

**Comment by miniscruff** [comment]
> Work around is to keep all change fragments (batch version -k) since we started a new version until it is really merge into CHANGELOG.md

This is not a workaround, this is the intention. When you generate a version it is expected you release that version, versions are immutable and thus there is no mechanism to update versions. As you mentioned you should not use batch until you are ready to release. When you are ready you should run batch, then make any manual changes you may or may not need, then run merge, then release.

**Comment by llaville** [comment]
So, if `batch` command is only supposed to run once by version, what the `keep` option is for ?

**Comment by miniscruff** [comment]
> So, if `batch` command is only supposed to run once by version, what the `keep` option is for ?

https://github.com/miniscruff/changie/discussions/237 keep comes from this discussion about pre-releases.

**Comment by miniscruff** [comment]
Generally speaking it is meant for the pre-release flow where you want to keep around pre-release version fragments to build a unified version on release. For example beta1, beta2, rc1, v2.0 combines all releases. If you are still working on the next version you should not be batching until you are ready to release.

**Comment by llaville** [comment]
Ok, as it is the intention of `batch` command. I propose to display a warning message and a `--force` option to override contents.
Final choice should be User !

**Comment by miniscruff** [comment]
I think the same rules would apply to `batch` as it would with `init` in that, if the version already exists it should do nothing unless `--force` is applied. I will make a separate issue for that and put it as another "good first issue".

**Comment by miniscruff** [comment]
Closing in favor of #406
