### ISSUE TITLE
Allowing accented characters in a change's body

### ISSUE THREAD

**Issue by robin-vagner** [miniscruff/changie#492]
We are a french team of developers using `changie` for our internal tools and since our user base is french as well, we would like to be able to use accented characters in our changelogs.

Currently it seems any accented character is ignored when typing the change's body.

This is not a vital feature since we can write understandable french without accents, but it would be nice to have :)

**Comment by miniscruff** [comment]
Hey Robin, can you give some examples? I imagine this would either be an issue with bubble tea or the input prompt parsing? I can take a look though either way.

**Comment by robin-vagner** [comment]
Hey, I just tried it and copy-pasting an accented character does work in the vscode integrated terminal. Typing it regularly still does nothing however ...

But thanks for the workaround, we can work with this in the meantime.

I just want to add :  thank for making changie, it's an awesome tool !

**Comment by miniscruff** [comment]
I traced this issue back to the bubbletea text input example and am having the same issues, this seems to be terminal specific so I am guessing there is some sort of export we need to add. Will keep my eye out on anything I find.

**Comment by miniscruff** [comment]
Closing as its not directly related to changie and I really have no way of fixing this, reopen if you think otherwise.
