### ISSUE TITLE
Add option to include unreleased changes when merging

### ISSUE THREAD

**Issue by miniscruff** [miniscruff/changie#503]
```shell
changie merge --include-unreleased=<header>
```

The idea here is to run the equivalent of a batch as the latest version at the top of the changelog. Including unreleased without any unreleased should continue as normal. 

The value of the parameter is the version header so you can do:
```shell
changie merge --include-unreleased="## Coming Soon"
```

_Originally posted by @sheldonhull in https://github.com/miniscruff/changie/discussions/488#discussioncomment-5943537_

**Comment by sheldonhull** [comment]
This is more intuitive. I like that.
