### ISSUE TITLE
Document using yq to query configuration

### ISSUE THREAD

**Issue by miniscruff** [miniscruff/changie#551]
**Describe the solution you'd like**
Small section on the new docs about how to use `yq`, and a few examples, to pull out data from the .changie.yaml file for use in other scripts.

**Describe alternatives you've considered**
Writing a config command but that's a bit more work then we need

**Comment by sheldonhull** [comment]
This might help: [workflow](https://github.com/DelineaXPM/github-workflows/blob/d6802c3ede573178a93104672e05993a775fd3d8/.github/workflows/changie-trigger-release.yml#L71) where I use yq to parse aqua file. If you give me a scenario on how I'd use with changie let me know and I'd be glad to throw a couple sample ones up here to save you the work :-)
