### ISSUE TITLE
Support multiple projects in a single change

### ISSUE THREAD

**Issue by fsmaia** [miniscruff/changie#571]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
When the projects feature is configured, `changie new` only allows a single project per change.

**Describe alternatives you've considered**
Asking users to repeat the same change for multiple projects

**Additional context**
This is very useful for monorepos with shared packages, in which a package change affects multiple projects

**Comment by miniscruff** [comment]
Hmm, that is a good point, I wonder if using a multi-select would be more appropriate for projects. I wonder if it should be part of the config to choose between multi-select and single select.

**Comment by fsmaia** [comment]
Yep! It's tricky to decide if single vs multi-select should be configurable.

My personal choice is to always enable multi-select, as I can't think of a clear use case for restricting that every change should only belong to one project (and if so, the users will pick only one, as a sane default behavior).

**Comment by fsmaia** [comment]
Btw I'm available to implement this change

**Comment by miniscruff** [comment]
Yea sure, that would be good. Let me know if you need any onboarding help.

**Comment by TheSpyder** [comment]
> I can't think of a clear use case for restricting that every change should only belong to one project

I can 😉  but I'll log a new ticket for my concerns after upgrading to 1.16
