### ISSUE TITLE
Replacements API documentation missing

### ISSUE THREAD

**Issue by katerberg** [miniscruff/changie#573]
Thanks for submitting a bug report, please fill in the following details.

**Description**
There is a link to the Replacements docs that appears to be broken

**Reproduction Steps**
1. Go to https://changie.dev/integrations/nodejs/
1. Click on the link to https://changie.dev/config/replacements/
1. See the 404 page

**What happened**
404 page with no docs on the replacement api

**Expected behavior**
I would expect to see some documentation of the code in `core/replacement.go`.

**Comment by miniscruff** [comment]
Hmm I think it's supposed to link here https://changie.dev/config/#config-replacements

Arguably not a very detailed section though.

**Comment by katerberg** [comment]
That would have been really helpful since I spent about an hour trying to figure out why `changie batch` didn't run it 😢 

I'll try to give this update a shot later today!
