### ISSUE TITLE
make lint error

### ISSUE THREAD

**Issue by katerberg** [miniscruff/changie#574]
Thanks for submitting a bug report, please fill in the following details.

**Description**

There is a linting error around the usage of `.md` constant.

**Reproduction Steps**

1. Install go
1. Install goimports
1. Install other two required libraries
1. Run `make lint` on `main`.
1. See error

**What happened**

```sh
~/src/changie$ make lint
goimports -w -local github.com/miniscruff/changie .
golangci-lint run ./...
core/utils_test.go:285:54: string `.md` has 6 occurrences, make it a constant (goconst)
					&then.MockDirEntry{MockName: tc.latestVersion + ".md"},
```

**Expected behavior**

Clean linting command

**Additional context**

This is on a Mac and I installed everything from `brew`.

`go version go1.21.3 darwin/arm64`
`go install golang.org/x/tools/cmd/goimports@latest`

**Comment by miniscruff** [comment]
What version of golangci lint are you using?

**Comment by miniscruff** [comment]
There must of been a config change or something in 1.55 but yea, it should be fixed now.
