### ISSUE TITLE
Allow `changie batch` to operate across all projects within a monorepo using a single command.

### ISSUE THREAD

**Issue by ArvinJ-H** [miniscruff/changie#580]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
`changie batch` should ideally work similarly to `changie merge`, where it automatically `batch` all the projects within the mono repo, instead of having to run `batch` for all projects in the mono repo

**Describe alternatives you've considered**
Having a custom script to run `changie batch` on a list of repo names.

**Comment by miniscruff** [comment]
Do you mean specifically for auto mode, or does all of your projects have the same version?

**Comment by TheSpyder** [comment]
`auto` is what I was thinking for this, but yes having it support the normal batch versioning would be nice. We don't have all projects at the same version today, but it would make some things easier so it might happen.

**Comment by miniscruff** [comment]
It would be reasonable to allow `changie batch auto` to apply to all projects as each one would calculate the bump value based on auto rules. However, in all other cases it is expected that each projects versions are different and that bumping them all in tandem would not apply.

If you are just having one version for all projects and are releasing them at the same time, you wouldn't need the monorepo support and could just use a single shared changelog.
