### ISSUE TITLE
simplify the docker run command and base container

### ISSUE THREAD

**Issue by sheldonhull** [miniscruff/changie#626]
Would you be up for a PR for a [chainguard based image](https://images.chainguard.dev/directory/image/static/versions) that should simplify the docker run option? They are well maintained secured images and very tiny.

```shell
docker run \
    --mount type=bind,source=$PWD,target=/src \
    -w /src \
    -it \
    --user $(id -u ${USER}):$(id -g ${USER}) \
    ghcr.io/miniscruff/changie \
    new
```

```
docker run -it --rm $(PWD):/app ghcr.io/miniscruff/changie new
```

It's still really small, but I've moved away from scratch to the chainguard nonroot static binary image and it's a great default to use, and has default nonroot user and such set. Should trim down the size of run instructions.

**Comment by miniscruff** [comment]
I could maybe add an extra docker image in goreleaser but I don't think modifying the original will be a good idea. Not sure of `ghcr.io/miniscruff/changie:chainguard` is a good idea either though. Tbh the docker image was more of an after thought.

**Comment by miniscruff** [comment]
Kinda forgot about this but I think realistically its better to leave it as is considering docker is probably the least common method of using changie as it is.
