### ISSUE TITLE
Recursively look for `.changie.yml`

### ISSUE THREAD

**Issue by lachlancannon** [miniscruff/changie#651]
**Is your feature request related to a problem? Please describe.**

To keep our project's changie configuration consistent we have a single `.changie.yml` at the top level of our project, but since we're always working in sub directories we need to do a lot of directory switching to use changie.

**Describe the solution you'd like**

A lot of similar tools support recursively searching higher level directories for their configuration files. This seems like the easiest and best solution for this.

**Describe alternatives you've considered**

It might be possible to just use a quick bash wrapper for my own purposes, but it seems like this would be an annoyance for a lot of other users too.

**Additional context**

-

**Comment by miniscruff** [comment]
I think this is fair and understandable. I am open to pull requests but may also work on changie during my next stream. I want to give the huh package a try.

**Comment by JamesToohey** [comment]
@miniscruff thanks for doing this one so promptly! Is there a way we can financially contribute to Changie as a thank you?

**Comment by miniscruff** [comment]
> @miniscruff thanks for doing this one so promptly! Is there a way we can financially contribute to Changie as a thank you?

Hmm maybe I will set something up in the future. But for now just using and sharing is enough.
