### ISSUE TITLE
New command to get next release version based on part.

### ISSUE THREAD

**Issue by cassiobotaro** [miniscruff/changie#98]
**Is your feature request related to a problem? Please describe.**
Is not a problem but can be useful a command `changie next patch` who echoes next version based on latest.

**Describe the solution you'd like**
Create a new command to echoes next release based on latest. (see additional context).

**Describe alternatives you've considered**
Add into batch command directly a conditional to check if "major", "minor" or "patch", get version using latest pipeline, then pass forward next version.  

**Additional context**
![image](https://user-images.githubusercontent.com/3127847/117589967-8a67aa80-b103-11eb-8994-67cefa559ca2.png)

**Comment by miniscruff** [comment]
Mind creating a separate issue for supporting major/minor/patch as an option to the batch command, I like that idea.
